/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FindProfessionalsRouteImport } from './routes/find-professionals'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BecomeAProviderRouteImport } from './routes/become-a-provider'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupportIndexRouteImport } from './routes/support.index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SupportUsersRouteImport } from './routes/support.users'
import { Route as SupportTicketsRouteImport } from './routes/support.tickets'
import { Route as SupportReportsRouteImport } from './routes/support.reports'
import { Route as SupportFaqsRouteImport } from './routes/support.faqs'
import { Route as SupportDisputesRouteImport } from './routes/support.disputes'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminTeamRouteImport } from './routes/super-admin.team'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin.settings'
import { Route as SuperAdminSecurityRouteImport } from './routes/super-admin.security'
import { Route as SuperAdminFeaturesRouteImport } from './routes/super-admin.features'
import { Route as SuperAdminBackupsRouteImport } from './routes/super-admin.backups'
import { Route as SuperAdminApplicationsRouteImport } from './routes/super-admin.applications'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as ProviderWalletRouteImport } from './routes/provider.wallet'
import { Route as ProviderSettingsRouteImport } from './routes/provider.settings'
import { Route as ProviderPortfolioRouteImport } from './routes/provider.portfolio'
import { Route as ProviderMessagesRouteImport } from './routes/provider.messages'
import { Route as ProviderBookingsRouteImport } from './routes/provider.bookings'
import { Route as ProviderAvailabilityRouteImport } from './routes/provider.availability'
import { Route as ProviderAnalyticsRouteImport } from './routes/provider.analytics'
import { Route as DashboardWalletRouteImport } from './routes/dashboard.wallet'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardBookingsRouteImport } from './routes/dashboard.bookings'
import { Route as BecomeAProviderApplyRouteImport } from './routes/become-a-provider.apply'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'

// NOTE: Full route tree body continues - if truncated, run `npx @tanstack/router-cli generate`
export { rootRouteImport }
const TermsRoute = TermsRouteImport.update({ id: '/terms', path: '/terms', getParentRoute: () => rootRouteImport } as any)
const SupportRoute = SupportRouteImport.update({ id: '/support', path: '/support', getParentRoute: () => rootRouteImport } as any)
const SuperAdminRoute = SuperAdminRouteImport.update({ id: '/super-admin', path: '/super-admin', getParentRoute: () => rootRouteImport } as any)
const SignupRoute = SignupRouteImport.update({ id: '/signup', path: '/signup', getParentRoute: () => rootRouteImport } as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({ id: '/reset-password', path: '/reset-password', getParentRoute: () => rootRouteImport } as any)
const ProviderRoute = ProviderRouteImport.update({ id: '/provider', path: '/provider', getParentRoute: () => rootRouteImport } as any)
const PrivacyRoute = PrivacyRouteImport.update({ id: '/privacy', path: '/privacy', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const HowItWorksRoute = HowItWorksRouteImport.update({ id: '/how-it-works', path: '/how-it-works', getParentRoute: () => rootRouteImport } as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({ id: '/forgot-password', path: '/forgot-password', getParentRoute: () => rootRouteImport } as any)
const FindProfessionalsRoute = FindProfessionalsRouteImport.update({ id: '/find-professionals', path: '/find-professionals', getParentRoute: () => rootRouteImport } as any)
const FeedRoute = FeedRouteImport.update({ id: '/feed', path: '/feed', getParentRoute: () => rootRouteImport } as any)
const FaqRoute = FaqRouteImport.update({ id: '/faq', path: '/faq', getParentRoute: () => rootRouteImport } as any)
const DirectoryRoute = DirectoryRouteImport.update({ id: '/directory', path: '/directory', getParentRoute: () => rootRouteImport } as any)
const DashboardRoute = DashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => rootRouteImport } as any)
const ContactRoute = ContactRouteImport.update({ id: '/contact', path: '/contact', getParentRoute: () => rootRouteImport } as any)
const CategoriesRoute = CategoriesRouteImport.update({ id: '/categories', path: '/categories', getParentRoute: () => rootRouteImport } as any)
const BecomeAProviderRoute = BecomeAProviderRouteImport.update({ id: '/become-a-provider', path: '/become-a-provider', getParentRoute: () => rootRouteImport } as any)
const AdminRoute = AdminRouteImport.update({ id: '/admin', path: '/admin', getParentRoute: () => rootRouteImport } as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({ id: '/access-denied', path: '/access-denied', getParentRoute: () => rootRouteImport } as any)
const AboutRoute = AboutRouteImport.update({ id: '/about', path: '/about', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const BecomeAProviderApplyRoute = BecomeAProviderApplyRouteImport.update({ id: '/apply', path: '/apply', getParentRoute: () => BecomeAProviderRoute } as any)
const SupportIndexRoute = SupportIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => SupportRoute } as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => SuperAdminRoute } as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => ProviderRoute } as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => DashboardRoute } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AdminRoute } as any)
const UUsernameRoute = UUsernameRouteImport.update({ id: '/u/$username', path: '/u/$username', getParentRoute: () => rootRouteImport } as any)

const BecomeAProviderRouteWithChildren = BecomeAProviderRoute._addFileChildren({ BecomeAProviderApplyRoute })
const DashboardRouteWithChildren = DashboardRoute._addFileChildren({ DashboardIndexRoute })
const ProviderRouteWithChildren = ProviderRoute._addFileChildren({ ProviderIndexRoute })
const AdminRouteWithChildren = AdminRoute._addFileChildren({ AdminIndexRoute })
const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren({ SuperAdminIndexRoute })
const SupportRouteWithChildren = SupportRoute._addFileChildren({ SupportIndexRoute })

export const routeTree = rootRouteImport._addFileChildren({
  IndexRoute,
  AboutRoute,
  AccessDeniedRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeAProviderRoute: BecomeAProviderRouteWithChildren,
  CategoriesRoute,
  ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DirectoryRoute,
  FaqRoute,
  FeedRoute,
  FindProfessionalsRoute,
  ForgotPasswordRoute,
  HowItWorksRoute,
  LoginRoute,
  PrivacyRoute,
  ProviderRoute: ProviderRouteWithChildren,
  ResetPasswordRoute,
  SignupRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  SupportRoute: SupportRouteWithChildren,
  TermsRoute,
  UUsernameRoute,
})
